{
 "title": "WSPR-main",
 "tags": [ "wspr" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "bandl",
    "label": "Band",
    "query": "SHOW tag VALUES FROM \"wspr_main\" WITH KEY = \"band\""
   },
   {
    "name": "rprtr",
    "query": "SHOW tag VALUES FROM \"wspr_main\" WITH KEY = \"reporter\""
   },
   {
    "name": "beacon",
    "query": "SHOW tag VALUES FROM \"wspr_main\" WITH KEY = \"call\" "
   },
   {
    "name": "rprtr2",
    "query": "SHOW tag VALUES FROM \"wspr_main\" WITH KEY = \"reporter\""
   },
   {
    "name": "interval",
    "query": "2m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "localstn", "query": "0,30,50,100,150,200,300,500" }
  ]
 },
 "panels": [
  {
   "title": "Header",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "DK5HH & PA7T WSPRlive analysis",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "content": "<center>Select reporter of your choice from drop down menu to analyze propagation to his location / antenna.</center>\n<center>Select reporter2 for comparison to reporter 1 - selectors could select more than 1; bandl selects the observed bands.</center> \n<center>Select beacon call sign for comparison on all bands; you can deselect all, type the first characters to reduce the list. click to end selction</center>"
    }
   ]
  },
  {
   "title": "Overview and specials for $rprtr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Relative Band Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_band m",
     "groupBy": [
      { "params": [ "band" ], "type": "tag" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"reporter\" =~ /^$rprtr$/  AND \"dist\" > $localstn AND $timeFilter GROUP BY \"band\"",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "reporter", "operator": "=", "value": "DK5HH" }
     ]
    }
   ]
  },
  {
   "title": "Total receptions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "wspr_redpitaya",
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"reporter\" =~ /^$rprtr$/ AND \"dist\" > $localstn AND $timeFilter",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "reporter", "operator": "=~", "value": "/^$rprtr$/" }
     ]
    }
   ]
  },
  {
   "title": "counts / h",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"reporter\" =~ /^$rprtr$/ AND \"dist\" > $localstn AND $timeFilter",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "The selected BEACONs $beacon SNR",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band m $tag_comment",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "band" ], "type": "tag" },
      { "params": [ "comment" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "wspr_main",
     "query": "select snr from wspr_main where (\"call\" =~ /^$beacon$/) group by band, comment",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "reporter", "operator": "=~", "value": "/^$beacon$/" }
     ]
    }
   ]
  },
  { "title": "DX info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Far West DX dist > 5000 km (selected bands )",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band m, $tag_call SNR",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT distinct(\"snr\") FROM \"wspr_main\" WHERE \"az\"  > 200 AND \"dist\" >5000 AND \"reporter\" =~ /^$rprtr$/  and \"band\" =~ /^$bandl$/ AND $timeFilter GROUP BY time(2m),\"band\",\"call\",\"comment\"",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "az", "operator": "=", "value": "200" }
     ]
    }
   ]
  },
  {
   "title": "Far East DX dist > 5000 km (selected bands)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band m, $tag_call SNR",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "band" ], "type": "tag" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT distinct(\"snr\") FROM \"wspr_main\" WHERE \"az\"  < 160 AND \"dist\" >5000 AND \"reporter\" =~ /^$rprtr$/ and \"band\" =~ /^$bandl$/ AND $timeFilter GROUP BY time(2m),\"band\",\"call\",\"comment\"",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "az", "operator": "=~", "value": "/1../" },
      { "condition": "AND", "key": "dist", "operator": "=~", "value": "/[89].../" },
      { "condition": "OR", "key": "dist", "operator": "=~", "value": "/1..../" }
     ]
    }
   ]
  },
  {
   "title": "WSPR reception in 20 min intervals by $rprtr and $rprtr2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "repeat": "bandl",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$bandl m band",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"snr\") FROM \"wspr_main\" WHERE \"band\" =~ /^$bandl$/ AND (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND $timeFilter GROUP BY time(20m) , \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Sum of all bands / hour (based on 10 min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_reporter $tag_comment",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT count(\"snr\")  * 6 FROM \"wspr_main\" WHERE (\"reporter\" =~ /^$rprtr$/ or  \"reporter\" =~ /^$rprtr2$/) AND \"dist\" > $localstn AND $timeFilter GROUP BY time(10m), \"reporter\", \"comment\"",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " * 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "reporter", "operator": "=~", "value": "/^$rprtr$/" }
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "All bands - moving average (w=3) based on 10 min - scaled to  spots per hour",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band m",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "band" ], "type": "tag" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT moving_average(count(\"snr\"),3)  * 6 FROM \"wspr_main\" WHERE \"reporter\" =~ /^$rprtr$/ AND \"dist\" > $localstn AND $timeFilter GROUP BY time(10m), \"band\"",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ " * 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "reporter", "operator": "=~", "value": "/^$rprtr$/" }
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "all Nederland",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band m, $tag_call",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "band" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT distinct(\"snr\") FROM \"wspr_main\" WHERE \"call\" =~ /^P[A-I].*$/ AND \"reporter\" =~ /^$rprtr$/ AND $timeFilter GROUP BY time($interval), \"band\" ,\"call\" fill(null)",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "call", "operator": "=~", "value": "/P[A-I].*/" },
      { "condition": "AND", "key": "reporter", "operator": "=~", "value": "/^$rprtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Comparative SNR of  Beacons $beacon",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band m $tag_reporter",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"snr\") FROM \"wspr_main\" WHERE \"call\" =~ /^$beacon$/ AND $timeFilter GROUP BY time(2m), \"band\", \"reporter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "short-skips in EU: mean(Distance) - locators J,I,K, (by 20min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "band" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT mean(\"dist\") FROM \"wspr_main\" WHERE \"band\" =~ /[12]/ AND \"loc\" =~ /^[JIK][MNOP].*/ and \"dist\" >100 AND \"dist\" < 2000 AND $timeFilter GROUP BY time(20m), \"band\" fill(none)",
     "select": [
      [
       { "params": [ "dist" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "band", "operator": "=~", "value": "/..[12]/" },
      { "condition": "AND", "key": "loc", "operator": "=~", "value": "/^J.*/" }
     ]
    }
   ]
  },
  {
   "title": "short skip in EU - count() in locators J,I,K, (by 20min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_band",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wspr_redpitaya",
     "query": "SELECT count(\"dist\") FROM \"wspr_main\" WHERE \"band\" =~ /[12]/ AND \"loc\" =~ /^[JIK][MNOP].*/ AND \"dist\" > 100 AND \"dist\" < 2000 AND $timeFilter GROUP BY time(20m), \"band\" fill(none)",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IRC Chat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chat - use your call as nickname",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
     "content": "<iframe src=\"https://kiwiirc.com/client/irc.freenode.net/?nick=kiwi_pa7t_nl|?&theme=mini#wspr\" style=\"border:0; width:100%; height:450px;\"></iframe>"
    }
   ]
  }
 ]
}